lib/notes_web/router.ex
defmodule NotesWeb.Router do
  use NotesWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", NotesWeb do
    pipe_through :browser

    get "/", BlogController, :index
    get "/blog/:id", BlogController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", NotesWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: NotesWeb.Telemetry
    end
  end
end

lib/notes/application.ex
defmodule Notes.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    children = [
      # Start the Telemetry supervisor
      NotesWeb.Telemetry,
      # Start the PubSub system
      {Phoenix.PubSub, name: Notes.PubSub},
      # Start the Endpoint (http/https)
      NotesWeb.Endpoint
      # Start a worker by calling: Notes.Worker.start_link(arg)
      # {Notes.Worker, arg}
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Notes.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    NotesWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/notes/blog/blog.ex
defmodule Notes.Blog do
  alias Notes.Blog.Post

  use NimblePublisher,
    build: Post,
    from: Application.app_dir(:notes, "priv/posts/**/*.md"),
    as: :posts,
    highlighters: [:makeup_elixir, :makeup_erlang]

  @posts Enum.sort_by(@posts, & &1.date, {:desc, Date})

  @tags @posts |> Enum.flat_map(& &1.tags) |> Enum.uniq() |> Enum.sort()

  def all_posts, do: @posts
  def all_tags, do: @tags

  def published_posts, do: Enum.filter(all_posts(), &(&1.published == true))
  def recent_posts(num \\ 5), do: Enum.take(published_posts(), num)

  defmodule NotFoundError, do: defexception [:message, plug_status: 404]

  def get_post_by_id!(id) do
    Enum.find(all_posts(), &(&1.id == id)) ||
      raise NotFoundError, "post with id=#{id} not found"
  end

  def get_posts_by_tag!(tag) do
    case Enum.filter(all_posts(), &(tag in &1.tags)) do
      [] -> raise NotFoundError, "posts with tag=#{tag} not found"
      posts -> posts
    end
  end
end

lib/notes/blog/post.ex
defmodule Notes.Blog.Post do
  @enforce_keys [:id, :author, :title, :body, :description, :tags, :date]
  defstruct [:id, :author, :title, :body, :description, :tags, :date]

  def build(filename, attrs, body) do
    [year, month_day_id] = filename |> Path.rootname() |> Path.split() |> Enum.take(-2)
    [month, day, id] = String.split(month_day_id, "-", parts: 3)
    date = Date.from_iso8601!("#{year}-#{month}-#{day}")
    struct!(__MODULE__, [id: id, date: date, body: body] ++ Map.to_list(attrs))
  end
end

lib/notes_web/controllers/blog_controller.ex
defmodule NotesWeb.BlogController do
  use NotesWeb, :controller

  alias Notes.Blog

  def index(conn, _params) do
    render(conn, "index.html", posts: Blog.all_posts())
  end

  def show(conn, %{"id" => id}) do
    render(conn, "show.html", post: Blog.get_post_by_id!(id))
  end
end

lib/notes_web/controllers/page_controller.ex
defmodule NotesWeb.PageController do
  use NotesWeb, :controller

  def index(conn, _params) do
    render(conn, "index.html")
  end
end

lib/notes_web/views/blog_view.ex
defmodule NotesWeb.BlogView do
  use NotesWeb, :view
end

lib/notes_web/views/error_view.ex
defmodule NotesWeb.ErrorView do
  use NotesWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/notes_web/views/layout_view.ex
defmodule NotesWeb.LayoutView do
  use NotesWeb, :view
end

lib/notes_web/views/page_view.ex
defmodule NotesWeb.PageView do
  use NotesWeb, :view
end

lib/notes_web/templates/blog/index.html.eex
<h4>Posts</h4>

<%= for post <- @posts do %>
  <div id="<%= post.id %>" style="margin-bottom: 1rem;">
    <span>
      <time><%= post.date %></time>
    </span> <>

    <h3> <%= link post.title, to: Routes.blog_path(@conn, :show, post), class: "post-title" %></h3>

    <!-- <p>
      Tagged as <%= Enum.join(post.tags, ", ") %>
    </p> -->

    <!-- <%= raw post.description %> -->
  </div>
<% end %>

lib/notes_web/templates/blog/show.html.eex
<%= link "← All posts", to: Routes.blog_path(@conn, :index), class: "link-back" %>

<h1 class="post-title"><%= @post.title %></h1>

<i><p><time><%= @post.date %></time> by <%= @post.author %></p><i>

<i><p>Tagged as <%= Enum.join(@post.tags, ", ") %></p></i>

<%= raw @post.body %>

lib/notes_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Notes · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <nav role="navigation">
          <%= link "Luiz Alberto Cattani", to: Routes.blog_path(@conn, :index), class: "post-title" %>
        </nav>
      </section>
    </header>
    <main role="main" class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <%= @inner_content %>
    </main>
  </body>
</html>

lib/notes_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>Peace of mind from prototype to production</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.5/CHANGELOG.md">v1.5 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
      <li>
        <a href="https://elixir-slackin.herokuapp.com/">Elixir on Slack</a>
      </li>
    </ul>
  </article>
</section>